# Generated by Django 5.2.7 on 2025-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_seats_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
