# Generated by Django 5.2.7 on 2025-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bus_route_schedule_seat_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('SEATER_NON_AC', 'Seater Non-A/C'), ('SLEEPER_NON_AC', 'Sleeper Non-A/C'), ('SEATER_AC', 'Seater A/C'), ('SLEEPER_AC', 'Sleeper A/C')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('WINDOW', 'window'), ('AISLE', 'aisle'), ('MIDDLE', 'middle'), ('UPPER', 'upper'), ('LOWER', 'lower')], max_length=10),
        ),
    ]
