# Generated by Django 5.2.7 on 2025-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bus_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('SEATER_NON_AC', 'Seater Non-A/C'), ('SLEEPER_NON_AC', 'Sleeper Non-A/C'), ('SEATER_AC', 'Seater A/C'), ('SLEEPER_AC', 'Sleeper A/C'), ('SLEEPER & SEATER_AC', 'Sleeper/Seater A/C')], max_length=50),
        ),
    ]
