# Generated by Django 5.2.7 on 2025-11-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bus_bus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'managed': False},
        ),
    ]
