# Generated by Django 5.2.7 on 2025-11-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appuser_payment_city_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='bus',
            table='bus',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='seat',
            table='seat',
        ),
    ]
