# Generated by Django 5.2.7 on 2025-10-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegoooapp', '0002_bus_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wegoooapp.bus_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wegoooapp.user')),
            ],
        ),
    ]
