# Generated by Django 5.2.7 on 2025-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegoooapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='route_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255, unique=True)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
            ],
        ),
    ]
