# Generated by Django 5.2.7 on 2025-10-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegoooapp', '0004_route_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bus_details',
            new_name='BusDetails',
        ),
        migrations.RenameModel(
            old_name='route_info',
            new_name='RouteInfo',
        ),
    ]
